# Generated by Django 3.2.16 on 2023-07-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0006_auto_20230710_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='tag',
            new_name='tags',
        ),
    ]
